export * from "./capitalizeFirst";
export * from "./device";
export * from "./getDimensions";
export * from "./getGameTileKey";
export * from "./maybeAddTeamKeyToPlayer";
export * from "./playSound";
export * from "./renderInsideSvg";
export * from "./sessionStorage";
export * from "./types";
