/** This is an autogenerated file, please do not change this file directly. */
declare namespace AddNewStagedActionModuleScssModule {
    export interface IAddNewStagedActionModuleScss {
        addNewStagedAction: string;
        spawnNewTilesContainer: string;
    }
}

declare const AddNewStagedActionModuleScssModule: AddNewStagedActionModuleScssModule.IAddNewStagedActionModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: AddNewStagedActionModuleScssModule.IAddNewStagedActionModuleScss;
};

export = AddNewStagedActionModuleScssModule;
