/** This is an autogenerated file, please do not change this file directly. */
declare namespace StagedActionModuleScssModule {
    export interface IStagedActionModuleScss {
        buttonContainer: string;
        stagedContainer: string;
        stagedContainerInfo: string;
    }
}

declare const StagedActionModuleScssModule: StagedActionModuleScssModule.IStagedActionModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: StagedActionModuleScssModule.IStagedActionModuleScss;
};

export = StagedActionModuleScssModule;
