/** This is an autogenerated file, please do not change this file directly. */
declare namespace RegisterPlayerModuleScssModule {
    export interface IRegisterPlayerModuleScss {
        flash: string;
        nameInput: string;
        registerButtonContainer: string;
        registerPlayerContainer: string;
    }
}

declare const RegisterPlayerModuleScssModule: RegisterPlayerModuleScssModule.IRegisterPlayerModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: RegisterPlayerModuleScssModule.IRegisterPlayerModuleScss;
};

export = RegisterPlayerModuleScssModule;
