/** This is an autogenerated file, please do not change this file directly. */
declare namespace TeamSelectionModuleScssModule {
    export interface ITeamSelectionModuleScss {
        active: string;
        individualTeam: string;
        north: string;
        northActive: string;
        northBackground: string;
        northColor: string;
        northHover: string;
        northLine: string;
        northTitle: string;
        south: string;
        southActive: string;
        southBackground: string;
        southColor: string;
        southHover: string;
        southLine: string;
        southTitle: string;
        teamMember: string;
        teamMembersContainer: string;
        teamSelectionContainer: string;
        title: string;
    }
}

declare const TeamSelectionModuleScssModule: TeamSelectionModuleScssModule.ITeamSelectionModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: TeamSelectionModuleScssModule.ITeamSelectionModuleScss;
};

export = TeamSelectionModuleScssModule;
