/** This is an autogenerated file, please do not change this file directly. */
declare namespace PieceSvgModuleScssModule {
    export interface IPieceSvgModuleScss {
        north: string;
        northActive: string;
        northBackground: string;
        northColor: string;
        northHover: string;
        northLine: string;
        northTitle: string;
        south: string;
        southActive: string;
        southBackground: string;
        southColor: string;
        southHover: string;
        southLine: string;
        southTitle: string;
    }
}

declare const PieceSvgModuleScssModule: PieceSvgModuleScssModule.IPieceSvgModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: PieceSvgModuleScssModule.IPieceSvgModuleScss;
};

export = PieceSvgModuleScssModule;
