/** This is an autogenerated file, please do not change this file directly. */
declare namespace PieceModuleScssModule {
    export interface IPieceModuleScss {
        hidden: string;
        pieceContainer: string;
    }
}

declare const PieceModuleScssModule: PieceModuleScssModule.IPieceModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: PieceModuleScssModule.IPieceModuleScss;
};

export = PieceModuleScssModule;
