/** This is an autogenerated file, please do not change this file directly. */
declare namespace ActionsSidebarModuleScssModule {
    export interface IActionsSidebarModuleScss {
        actionsSidebar: string;
        bothTeamInformation: string;
        bothTeamsContainer: string;
        gameState: string;
        northActive: string;
        northBackground: string;
        northColor: string;
        northHover: string;
        northLine: string;
        northTitle: string;
        oneTeam: string;
        oneTeamScore: string;
        section: string;
        southActive: string;
        southBackground: string;
        southColor: string;
        southHover: string;
        southLine: string;
        southTitle: string;
        stagedActionsContainer: string;
        stagedActionsList: string;
        stagedActionsTitle: string;
        turn: string;
        turnAndGameSection: string;
        turnNumber: string;
        turnTitle: string;
    }
}

declare const ActionsSidebarModuleScssModule: ActionsSidebarModuleScssModule.IActionsSidebarModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ActionsSidebarModuleScssModule.IActionsSidebarModuleScss;
};

export = ActionsSidebarModuleScssModule;
