/** This is an autogenerated file, please do not change this file directly. */
declare namespace PiecePoolModuleScssModule {
    export interface IPiecePoolModuleScss {
        pieceContainer: string;
    }
}

declare const PiecePoolModuleScssModule: PiecePoolModuleScssModule.IPiecePoolModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: PiecePoolModuleScssModule.IPiecePoolModuleScss;
};

export = PiecePoolModuleScssModule;
