/** This is an autogenerated file, please do not change this file directly. */
declare namespace GameModuleScssModule {
    export interface IGameModuleScss {
        gameContainer: string;
        metadataContainer: string;
    }
}

declare const GameModuleScssModule: GameModuleScssModule.IGameModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: GameModuleScssModule.IGameModuleScss;
};

export = GameModuleScssModule;
