/** This is an autogenerated file, please do not change this file directly. */
declare namespace AllPlayersModuleScssModule {
    export interface IAllPlayersModuleScss {
        mainContainer: string;
    }
}

declare const AllPlayersModuleScssModule: AllPlayersModuleScssModule.IAllPlayersModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: AllPlayersModuleScssModule.IAllPlayersModuleScss;
};

export = AllPlayersModuleScssModule;
