/** This is an autogenerated file, please do not change this file directly. */
declare namespace SelfUpdatingTimerModuleScssModule {
    export interface ISelfUpdatingTimerModuleScss {
        green: string;
        red: string;
        yellow: string;
    }
}

declare const SelfUpdatingTimerModuleScssModule: SelfUpdatingTimerModuleScssModule.ISelfUpdatingTimerModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: SelfUpdatingTimerModuleScssModule.ISelfUpdatingTimerModuleScss;
};

export = SelfUpdatingTimerModuleScssModule;
