/** This is an autogenerated file, please do not change this file directly. */
declare namespace SocketHealthModuleScssModule {
    export interface ISocketHealthModuleScss {
        genericIndicator: string;
        green: string;
        red: string;
        socketContainer: string;
    }
}

declare const SocketHealthModuleScssModule: SocketHealthModuleScssModule.ISocketHealthModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: SocketHealthModuleScssModule.ISocketHealthModuleScss;
};

export = SocketHealthModuleScssModule;
