/** This is an autogenerated file, please do not change this file directly. */
declare namespace GameTileModuleScssModule {
    export interface IGameTileModuleScss {
        freeTile: string;
        northTile: string;
        southTile: string;
    }
}

declare const GameTileModuleScssModule: GameTileModuleScssModule.IGameTileModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: GameTileModuleScssModule.IGameTileModuleScss;
};

export = GameTileModuleScssModule;
