/** This is an autogenerated file, please do not change this file directly. */
declare namespace GameTileModuleScssModule {
    export interface IGameTileModuleScss {
        actionablePiece: string;
        canSelectTile: string;
        destroy: string;
        destroyedPiece: string;
        fadeIn: string;
        freeTile: string;
        isPartOfMoveAction: string;
        isPartOfSpawnAction: string;
        isPartOfSpecialAction: string;
        isSelectedTile: string;
        normalTile: string;
        northActive: string;
        northBackground: string;
        northColor: string;
        northHover: string;
        northLine: string;
        northTile: string;
        northTitle: string;
        score: string;
        scoredPiece: string;
        southActive: string;
        southBackground: string;
        southColor: string;
        southHover: string;
        southLine: string;
        southTile: string;
        southTitle: string;
        spawnOverAliveTile: string;
    }
}

declare const GameTileModuleScssModule: GameTileModuleScssModule.IGameTileModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: GameTileModuleScssModule.IGameTileModuleScss;
};

export = GameTileModuleScssModule;
