/** This is an autogenerated file, please do not change this file directly. */
declare namespace GameBoardModuleScssModule {
    export interface IGameBoardModuleScss {
        board: string;
        boardContainer: string;
        row: string;
    }
}

declare const GameBoardModuleScssModule: GameBoardModuleScssModule.IGameBoardModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: GameBoardModuleScssModule.IGameBoardModuleScss;
};

export = GameBoardModuleScssModule;
